name: Docker Publish API

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_for_changes.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install turbo
        run: npm install -g turbo@2.4.4 && npm install -g turbo-ignore
      - name: Check for changes
        id: check_for_changes
        run: npx turbo-ignore api --fallback=HEAD^1 && echo "has_changes=false" >> "$GITHUB_OUTPUT" || echo "has_changes=true" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install turbo
        run: npm install -g turbo@2.4.4
      - name: Login to Docker
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Build the Docker image
        run: docker build . --file apps/api/Dockerfile --tag ghcr.io/buildtheearth/website-node-backend:$(git rev-parse --short HEAD) --tag ghcr.io/buildtheearth/website-node-backend:latest
      - name: Docker push tag
        run: docker push ghcr.io/buildtheearth/website-node-backend:$(git rev-parse --short HEAD)
      - name: Docker push latest
        run: docker push ghcr.io/buildtheearth/website-node-backend:latest
